version: '2'
services:
  my-golang-app-run:
    container_name: my-golang-app-image
    build: .
    command: go run main.go deck.go
    volumes:
      - ./src:/go/src/app
    working_dir: /go/src/app
    ports:
      - "3030:3001"
    environment:
      PORT: 3001